plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Vania Clementine\\.gemini\\antigravity\\scratch\\pg95-claim-app\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Vania Clementine\\.gemini\\antigravity\\scratch\\pg95-claim-app"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]